import Config

# Configure your database
config :missionspace, Missionspace.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "missionspace_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :missionspace, MissionspaceWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "HYybgkxbO4bR3khuT8GicxC7iPK+IJv0HwtdAdcq09Me1Sg/qou2J1a3vyk2CNdN",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :missionspace, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Cloudflare R2 Storage (dev)
config :missionspace, :r2,
  access_key_id: "1b5295b87cb00967b206561b746646a0",
  secret_access_key: "35d385323c21282ed01ea41603e851750455623310aa9cf59c6fedc39289916b",
  bucket: "missionspace",
  host: "041b2d7bd4ad75659221d9d3edc332ac.r2.cloudflarestorage.com",
  region: "auto"

config :ex_aws,
  access_key_id: "1b5295b87cb00967b206561b746646a0",
  secret_access_key: "35d385323c21282ed01ea41603e851750455623310aa9cf59c6fedc39289916b",
  region: "auto"

config :ex_aws, :s3,
  scheme: "https://",
  host: "041b2d7bd4ad75659221d9d3edc332ac.r2.cloudflarestorage.com",
  region: "auto"

# Web Push (dev)
config :web_push_encryption, :vapid_details,
  subject: "mailto:dev@localhost",
  public_key:
    "BCdOUElSDkbS8lGf8ghJmfKd3H0u9D2MxJsFTAuXFEV0NxW8AzSfMfqQXyHfNr_IVDkR8fxbWJo0LMK4rFuRHyk",
  private_key: "lbZQqnMLkpeV0J_s3tLkGQj1OMP53Yf5gaKvsqFjef8"
